"""
Configuration file for Email Summarizer Pro
Do NOT edit this file manually. Use the app's setup screen instead.
"""

import os
import sys
from dotenv import load_dotenv

# Fix Unicode encoding for Windows
if sys.platform == 'win32' and sys.stdout is not None:
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Load environment variables from .env file
load_dotenv()

# ========== GMAIL API CONFIGURATION ==========
GMAIL_CREDENTIALS_FILE = 'credentials.json'
GMAIL_SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']
GMAIL_TOKEN_CACHE = 'token.pkl'

# ========== GEMINI API CONFIGURATION ==========
# Note: API key is loaded from .env file (set via app's setup screen)
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GEMINI_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
GEMINI_TEMPERATURE = 0.2
GEMINI_MAX_TOKENS = 2048

# ========== UI SETTINGS ==========
DEFAULT_EMAIL_COUNT = 5
DEFAULT_SUMMARIZE_ON_LOAD = False
PARALLEL_WORKERS = 4
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 850
MIN_WINDOW_WIDTH = 1100
MIN_WINDOW_HEIGHT = 650
